GET http://localhost:4321/api/distress/all
###
POST http://localhost:4321/api/distress/search
Content-Type: application/json

{
  "limit": 40,
  "title": "snake",
  "asc": 1
}

###
GET http://localhost:4321/api/users

###
POST http://localhost:4321/api/distress/new

{
  "author": "5a4fceeea9b75c111c7d95c2",
  "title": "Newest Latest",
  "description": "This is new one just done now",
  "image": "image_url",
  "category": "police",
  "location": "Nigeria",
  "tags": ["raid", "paid"] 
}