GET http://localhost:4322/api/users
###
POST http://distress-app.herokuapp.com/api/comments/new
Content-Type: application/json

{
  "distress": "5a65fd6e729c140014f735b0",
  "email": "ashinzekene@gmail.com",
  "text": "I also had the experience"
}