module.exports.categories = [
  'Airport',
  'Banking',
  'Commercial Tax, Sales Tax',
  'Customs',
  'Education',
  'Electricity and Power Supply',
  'Foreign Trade',
  'Forest',
  'Health Care',
  'Immigration',
  'Juduciary',
  'Others',
  'Pension',
  'Police',
  'Religious',
  'Telecommunication',
]; 